// Code generated by mockery v2.42.1. DO NOT EDIT.

package httpsig

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NonceGetterMock is an autogenerated mock type for the NonceGetter type
type NonceGetterMock struct {
	mock.Mock
}

type NonceGetterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *NonceGetterMock) EXPECT() *NonceGetterMock_Expecter {
	return &NonceGetterMock_Expecter{mock: &_m.Mock}
}

// GetNonce provides a mock function with given fields: ctx
func (_m *NonceGetterMock) GetNonce(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNonce")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NonceGetterMock_GetNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNonce'
type NonceGetterMock_GetNonce_Call struct {
	*mock.Call
}

// GetNonce is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NonceGetterMock_Expecter) GetNonce(ctx interface{}) *NonceGetterMock_GetNonce_Call {
	return &NonceGetterMock_GetNonce_Call{Call: _e.mock.On("GetNonce", ctx)}
}

func (_c *NonceGetterMock_GetNonce_Call) Run(run func(ctx context.Context)) *NonceGetterMock_GetNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *NonceGetterMock_GetNonce_Call) Return(_a0 string, _a1 error) *NonceGetterMock_GetNonce_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NonceGetterMock_GetNonce_Call) RunAndReturn(run func(context.Context) (string, error)) *NonceGetterMock_GetNonce_Call {
	_c.Call.Return(run)
	return _c
}

// NewNonceGetterMock creates a new instance of NonceGetterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNonceGetterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *NonceGetterMock {
	mock := &NonceGetterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
