// Code generated by mockery v2.42.1. DO NOT EDIT.

package httpsig

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NonceCheckerMock is an autogenerated mock type for the NonceChecker type
type NonceCheckerMock struct {
	mock.Mock
}

type NonceCheckerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *NonceCheckerMock) EXPECT() *NonceCheckerMock_Expecter {
	return &NonceCheckerMock_Expecter{mock: &_m.Mock}
}

// CheckNonce provides a mock function with given fields: ctx, nonce
func (_m *NonceCheckerMock) CheckNonce(ctx context.Context, nonce string) error {
	ret := _m.Called(ctx, nonce)

	if len(ret) == 0 {
		panic("no return value specified for CheckNonce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, nonce)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NonceCheckerMock_CheckNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNonce'
type NonceCheckerMock_CheckNonce_Call struct {
	*mock.Call
}

// CheckNonce is a helper method to define mock.On call
//   - ctx context.Context
//   - nonce string
func (_e *NonceCheckerMock_Expecter) CheckNonce(ctx interface{}, nonce interface{}) *NonceCheckerMock_CheckNonce_Call {
	return &NonceCheckerMock_CheckNonce_Call{Call: _e.mock.On("CheckNonce", ctx, nonce)}
}

func (_c *NonceCheckerMock_CheckNonce_Call) Run(run func(ctx context.Context, nonce string)) *NonceCheckerMock_CheckNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NonceCheckerMock_CheckNonce_Call) Return(_a0 error) *NonceCheckerMock_CheckNonce_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NonceCheckerMock_CheckNonce_Call) RunAndReturn(run func(context.Context, string) error) *NonceCheckerMock_CheckNonce_Call {
	_c.Call.Return(run)
	return _c
}

// NewNonceCheckerMock creates a new instance of NonceCheckerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNonceCheckerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *NonceCheckerMock {
	mock := &NonceCheckerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
